import json

colunas_significados = {
    "id_dt_ini": "Data de início",
    "id_dt_fin": "Data de fim",
    "id_cnpj": "CNPJ da empresa",
    "id_sped": "Identificador SPED",
    "ind_oper": "Indicador de operação",
    "reg": "Registro",
    "ind_tp_oper": "Indicador de tipo de operação",
    "ind_emit": "Indicador de emitente",
    "emit_doc": "Documento emitido",
    "cod_part": "Código do participante",
    "fornecedor": "Fornecedor",
    "cnpj": "CNPJ",
    "municipio": "codigo do Município",
    "nome_municipio": "Nome do município",
    "uf": "Unidade Federativa",
    "nome_uf_dest": "Nome da UF de destino",
    "cod_pais": "Código do país",
    "cst_desc": "Descrição do CST",
    "pais": "País",
    "cod_mod": "Código do modelo",
    "cod_sit": "Código da situação",
    "cod_sit_doc": "Situação do documento",
    "ser": "Série",
    "num_doc": "Número do documento",
    "chv_nfe": "Chave da NFe",
    "chave_check": "Chave de verificação",
    "dt_doc": "Data do documento",
    "dt_e_s": "Data de entrada/saída",
    "reg_origem_entrada": "Registro de origem da entrada",
    "num_item": "Número do item",
    "cod_item": "Código do item",
    "descr_compl": "Descrição complementar",
    "ncm": "NCM (Nomenclatura Comum do Mercosul)",
    "classificacao_gerencial": "Classificação gerencial",
    "sub_classificacao_gerencial": "Sub-classificação gerencial",
    "qtd": "Quantidade",
    "unid": "Unidade federativa",
    "vl_item": "Valor do item",
    "vl_desc": "Valor do desconto",
    "ind_mov": "Indicador de movimentação",
    "cst_icms": "CST ICMS",
    "cfop": "CFOP (Código Fiscal de Operações e Prestações)",
    "tipo": "Tipo",
    "origem": "Origem",
    "cod_nat": "Código da natureza",
    "vl_bc_icms": "Valor da base de cálculo do ICMS",
    "aliq_icms": "Alíquota do ICMS",
    "vl_icms": "Valor do ICMS",
    "aliq_efetiva_icms": "Alíquota efetiva do ICMS",
    "vl_bc_icms_st": "Valor da base de cálculo do ICMS ST",
    "aliq_st": "Alíquota do ICMS ST",
    "vl_icms_st": "Valor do ICMS ST",
    "aliq_efetiva_icms_st": "Alíquota efetiva do ICMS ST",
    "vl_bc_ipi": "Valor da base de cálculo do IPI",
    "aliq_ipi": "Alíquota do IPI",
    "vl_ipi": "Valor do IPI",
    "aliq_efetiva_ipi": "Alíquota efetiva do IPI",
    "cfop_cst": "CFOP CST",
    "analise_credito": "Análise de crédito",
    "id_importation": "ID de importação",
    "id_tenant": "ID do tenant",
    "row_index": "Índice da linha",
    "dt_created": "Data de criação",
    "dt_updated": "Data de atualização",
    "year": "Ano",
    "month": "Mês",
    "day": "Dia",
    "hour": "Hora",
    "minute": "Minuto",
    "rown": "Número da linha",
    "ncm_abrev": "Abreviação do NCM",
    "cod_ncm_desc": "Descrição do código NCM",
    "cod_cst_desc": "Descrição do código CST",
    "sub_grupo": "Subgrupo",
    "imposto_cofins_pcofins": "Imposto COFINS (PIS/COFINS)",
    "segment": "Segmento",
    "abrev_origem": "Abreviação da origem",
    "vl_sld_credor_ant": "Valor do saldo credor anterior",
    "imposto_cofins_vbc": "Valor da base de cálculo do imposto COFINS",
    "uf_destinatario": "Unidade Federativa do destinatário",
    "v_frete": "Valor do frete",
    "notas_faltantes": "Notas faltantes",
    "abrev_tributacao": "Abreviação da tributação",
    "_id": "ID",
    "descr_aj": "Descrição do ajuste",
    "vicmsufremet": "Valor do ICMS enviado",
    "descr": "Descrição",
    "diff_vl_retencao_st": "Diferença de valor da retenção ST",
    "descr_sped": "Descrição do SPED",
    "outras_despesas": "Outras despesas",
    "vbc": "Valor base de cálculo",
    "vdespadu": "Valor de despesas aduaneiras",
    "sigla_uf": "Sigla da Unidade Federativa",
    "imposto_pis_vbc": "Valor da base de cálculo do imposto PIS",
    "vl_out_deb_st": "Valor de outros débitos ST",
    "total_ajuste_credtios_st": "Total de ajuste de créditos ST",
    "vfcpufdest": "Valor do FCP (Fundo de Combate à Pobreza) do destinatário",
    "operacao_saida_icms": "Operação de saída do ICMS",
    "imposto_cofins_vcofins": "Valor do imposto COFINS",
    "vii": "Valor do Imposto de Importação",
    "cnpj_name": "Nome associado ao CNPJ",
    "classificacao": "Classificação",
    "diff_sld_cred_ant_st": "Diferença de saldo credor anterior ST",
    "ind_mov_st": "Indicador de movimentação ST",
    "vl_tot_debitos_sped": "Valor total de débitos SPED",
    "porcentagem_faltante": "Porcentagem faltante",
    "descr_resumida": "Descrição resumida",
    "vl_aj_debitos": "Valor do ajuste de débitos",
    "nome": "Nome",
    "cfop_descricao_movimento": "Descrição do movimento CFOP",
    "imposto_ipi_cst": "Imposto IPI CST",
    "cfop_descr": "Descrição do CFOP",
    "notas_totais": "Notas totais",
    "vl_deducoes_st": "Valor das deduções ST",
    "imposto_ipi_vipi": "Valor do imposto IPI",
    "deb_esp": "Débitos especiais",
    "descr_abrev": "Descrição abreviada",
    "fonte_sped": "Fonte SPED",
    "qtd_trib": "Quantidade tributável",
    "vl_aj_creditos_st": "Valor do ajuste de créditos ST",
    "created_at": "Criado em",
    "pmvast_icms": "Pauta de Mercadoria com Valor Agregado do ICMS",
    "cpf_destinatario": "CPF do destinatário",
    "tenant_name": "Nome do tenant",
    "eantrib": "Código EAN tributável",
    "modbc_icms_st": "Modalidade de base de cálculo ICMS ST",
    "sped_competence": "Competência SPED",
    "vl_retencao_st": "Valor de retenção ST",
    "codigo_ibge": "Código IBGE",
    "vl_tot_aj_creditos": "Valor total de ajuste de créditos",
    "nome_tipo_aj": "Nome do tipo de ajuste",
    "vl_tot_debitos": "Valor total de débitos",
    "vl_tot_ded": "Valor total de deduções",
    "diff_sld_credor_ant": "Diferença de saldo credor anterior",
    "imposto_ipi_vbc": "Valor da base de cálculo do imposto IPI",
    "diff_tot_creditos": "Diferença total de créditos",
    "nf_key": "Chave da nota fiscal",
    "vl_or": "Valor original",
    "pais_destinatario": "País do destinatário",
    "sped": "SPED",
    "vstret": "Valor do ST retido",
    "tipo_icms": "Tipo de ICMS",
    "cfop_ext": "Extensão do CFOP",
    "vl_aj_apur": "Valor de ajuste apurado",
    "nome_uf": "Nome da Unidade Federativa",
    "vl_estornos_deb": "Valor de estornos de débitos",
    "aliq_st_icms": "Alíquota do ICMS ST",
    "dt_ini": "Data de início",
    "sub": "Substituição",
    "pfcpufddest": "Percentual do FCP do destinatário",
    "fonte": "Fonte",
    "expiration_date": "Data de expiração",
    "imposto_cofins_cst": "Imposto COFINS CST",
    "compras_transf": "Compras transferidas",
    "vl_unit": "Valor unitário",
    "vl_sld_cred_ant_st_sped": "Valor do saldo credor anterior ST no SPED",
    "cod_pais_destinatario": "Código do país do destinatário",
    "chave": "Chave",
    "pfcpst": "Percentual do FCP ST",
    "vl_devol_st_sped": "Valor de devolução ST no SPED",
    "branch_name_from_sped": "Nome da filial no SPED",
    "total_ajuste_creditos": "Total de ajuste de créditos",
    "deb_esp_st": "Débitos especiais ST",
    "diff_total_debito": "Diferença total de débito",
    "situacao": "Situação",
    "ie": "Inscrição Estadual",
    "desc_cst": "Descrição do CST",
    "vl_out_cred_st": "Valor de outros créditos ST",
    "cod_mum_destinatario": "Código do município do destinatário",
    "vbcfcpst": "Base de cálculo do FCP ST",
    "cst": "CST (Código de Situação Tributária)",
    "extipi": "Extensão do IPI",
    "vfcpst": "Valor do FCP ST",
    "tipo_operacao": "Tipo de operação",
    "bacen": "Código BACEN",
    "cest": "Código CEST",
    "filial": "Filial",
    "descricao": "Descrição",
    "dt_fim": "Data de fim",
    "id": "ID",
    "cnpj_destinatario": "CNPJ do destinatário",
    "dt_vcto": "Data de vencimento",
    "centralizacao": "Centralização",
    "total_ajuste_debitos_st": "Total de ajuste de débitos ST",
    "mot_des_icms": "Motivo de desoneração do ICMS",
    "final_sped": "Final SPED",
    "diff_vl_devol_st": "Diferença de valor de devolução ST",
    "picmsinter": "Percentual ICMS Interestadual",
    "vl_sld_credor_ant_sped": "Valor do saldo credor anterior no SPED",
    "tipo_aj": "Tipo de ajuste",
    "predbcst_imcs": "Predição da base de cálculo ICMS",
    "imposto_pis_vpis": "Valor do imposto PIS",
    "vl_icms_st": "Valor do ICMS ST",
    "company_name": "Nome da empresa",
    "class": "Classe",
    "unid_trib": "Unidade tributável",
    "cod_or": "Código de origem",
    "pred_bc": "Previsão da base de cálculo",
    "branch_name": "Nome da filial",
    "vl_apurado_no_periodo": "Valor apurado no período",
    "classificacao_adicional": "Classificação adicional",
    "chv_nfe": "Chave da NFe",
    "imposto_pis_cst": "Imposto PIS CST",
    "origem_ajuste": "Origem do ajuste",
    "apuracao_icms_st": "Apuração ICMS ST",
    "cod_aj": "Código do ajuste",
    "vl_sld_cred_ant_st": "Valor do saldo credor anterior ST",
    "custo": "Custo",
    "numeracao": "Numeração",
    "apuracao_icms": "Apuração ICMS",
    "cod_rec": "Código de receita",
    "vl_devol_st": "Valor de devolução ST",
    "chv_nf": "Chave da nota fiscal",
    "nome_mun_destinatario": "Nome do município do destinatário",
    "modulo_de_compras": "Módulo de compras",
    "vl_aj_debitos_st": "Valor do ajuste de débitos ST",
    "icms": "ICMS",
    "nome_destinatario": "Nome do destinatário",
    "viof": "Valor do IOF",
    "vfcp": "Valor do FCP",
    "vbcstret": "Base de cálculo do ST retido",
    "total_ajuste_debitos": "Total de ajuste de débitos",
    "dt_doc": "Data do documento",
    "cst_descr": "Descrição do CST",
    "has_nf": "Possui nota fiscal",
    "vl_tot_creditos_sped": "Valor total de créditos SPED",
    "vl_apurado_periodo_st": "Valor apurado no período ST",
    "dt_fin": "Data de fim",
    "grupo": "Grupo",
    "initial_sped": "Início SPED",
    "origem_destino": "Origem e destino",
    "embedding": "Incorporação",
    "vicmsufdest": "Valor do ICMS UF destino",
    "competencia": "Mes das notas fiscais",
    "vl_tot_aj_debitos": "Valor total de ajuste de débitos",
    "vl_aj_creditos": "Valor de ajuste de créditos",
    "deb_ou_cred": "Débito ou crédito",
    "vl_retencao_st_sped": "Valor de retenção ST no SPED",
    "cod_ibge": "Código IBGE",
    "v_seg": "Valor do seguro",
    "vl_estornos_cred": "Valor de estornos de créditos",
    "vl_ressarc_st": "Valor de ressarcimento ST",
    "cod_ean": "Código EAN",
    "imposto_pis_ppis": "Percentual do imposto PIS",
    "imposto_ipi_pipi": "Percentual do imposto IPI",
    "vbcufddest": "Base de cálculo UF destino",
    "vdeson": "Valor de desoneração",
    "picmsinterpart": "Percentual ICMS Interpart",
    "vl_tot_creditos": "Valor total de créditos",
}

json_string = json.dumps(colunas_significados, ensure_ascii=False, indent=4)